#!/usr/bin/env bash

set -e
set -x

HOME_DIR="$HOME"
CONFIG_DIR="$HOME/.config"

# Configs only stored in ~/ or $HOME
HOME_DIRS=("zsh" "tmux")
# Configs only stored in ~/.config/
CONFIG_DIRS=("nvim")

stow_it() {
    for h in ${HOME_DIRS[@]}; do
        stow --target="$HOME_DIR" $h
    done

    for c in ${CONFIG_DIRS[@]}; do
        # make a .config folder if it does not exist
        [[ ! -e $CONFIG_DIR ]] && mkdir "$CONFIG_DIR"
        [[ ! -e "$CONFIG_DIR/$c" ]] && mkdir "$CONFIG_DIR/$c"

        stow --target="$CONFIG_DIR/$c" --adopt -R $c
    done
}

stow_it

