[config]

[config.wallpaper]
set = true
command = 'waypaper --wallpaper "{{ image }}"'

[templates.hypr]
input_path = '~/dotfiles/matugen/hypr/colors.lua'
output_path = '~/dotfiles/hypr/hyprland/colors.lua'

[templates.wayle]
input_path = '~/dotfiles/matugen/wayle/colors.toml'
output_path = '~/dotfiles/wayle/matugen/colors.toml'
post_hook = 'wayle panel restart'

[templates.ghostty]
input_path = '~/dotfiles/matugen/ghostty/colors.ghostty'
output_path = '~/dotfiles/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.tmux]
input_path = '~/dotfiles/matugen/tmux/colors.conf'
output_path = '~/dotfiles/tmux/colors.conf'
post_hook = 'tmux source-file ~/dotfiles/tmux/tmux.conf'

[templates.nvim]
input_path = '~/dotfiles/matugen/nvim/colors.json'
output_path = '~/.local/share/dotfiles/nvim/colors.json'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.gtk3]
input_path = '~/dotfiles/matugen/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = "gsettings set org.gnome.desktop.interface color-scheme prefer-dark"

