terminal = "ghostty"
mainMod = "SUPER"
fileManager = "dolphin"
menu = "rofi -config ~/.config/rofi/config.rasi -show drun"
browser = "flatpak run com.brave.Browser"
bluetoothManager = "blueman-manager"
