terminal = "ghostty"
mainMod = "SUPER"
fileManager = "dolphin"
menu = "rofi -config ~/.config/rofi/config.rasi -show drun"
wallpaperFolder = os.getenv("HOME") .. "/Pictures/Wallpapers/"
browser = "brave"
bluetoothManager = "blueman-manager"
