require("hyprland.exec")
require("hyprland.general")
require("hyprland.animations")
require("hyprland.rules")
require("hyprland.env")
require("hyprland.binds")
require("hyprland.input")
require("hyprland.devices")
