set -g status-bg                "{{colors.surface.default.hex}}"

set -g @tmux-dotbar-bg         "{{colors.surface_container.default.hex}}"
set -g @tmux-dotbar-fg         "{{colors.surface_container_highest.default.hex}}"
set -g @tmux-dotbar-fg-current "{{colors.primary.default.hex}}"
set -g @tmux-dotbar-fg-session "{{colors.primary.default.hex}}"
set -g @tmux-dotbar-fg-prefix  "{{colors.surface_tint.default.hex}}"

set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default

