[general]
font-sans = "JetBrainsMono Nerd Font"

[bar]
scale = 0.6499999761581421
module-gap = 0.6
inset-edge = 0.5
inset-ends = 0.5
background-opacity = 75
rounding = "md"
button-variant = "basic"
button-gap = 1.2
button-label-size = 1.2
button-label-weight = "bold"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "hyprland-workspaces",
    "separator",
    "clock",
]
center = ["window-title"]
right = [
    "battery",
    "separator",
    "network",
    "separator",
    "volume",
    "separator",
    "systray",
    "separator",
    "dashboard",
]

[styling.palette]
bg = "#16161e"
surface = "#1a1b26"
elevated = "#202230"
fg = "#c0caf5"
fg-muted = "#a9b1d6"
primary = "#7aa2f7"
red = "#f7768e"
yellow = "#e0af68"
green = "#9ece6a"
blue = "#7dcfff"

[modules.clock]
format = "%a, %b %d, %Y %I:%M %p"
button-bg-color = "transparent"
label-color = "fg-default"
icon-show = false
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.dashboard]
icon-color = "fg-default"
icon-bg-color = "transparent"
dropdown-poweroff-command = "hyprshutdown -t 'Shutting down...' --post-cmd 'shutdown -P 0'"
dropdown-reboot-command = "hyprshutdown -t 'Rebooting...' --post-cmd 'reboot'"

[modules.hyprland-workspaces]
active-color = "blue"

[modules.window-title]
button-bg-color = "transparent"
icon-color = "fg-default"
icon-bg-color = "transparent"
label-color = "fg-default"

[modules.battery]
button-bg-color = "transparent"
label-color = "fg-default"
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.network]
button-bg-color = "transparent"
label-color = "fg-default"
label-show = false
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.volume]
button-bg-color = "transparent"
label-color = "fg-default"
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.systray]
button-bg-color = "transparent"
label-color = "fg-default"
icon-color = "fg-default"
icon-bg-color = "transparent"

