set -g status-bg                "#111318"

set -g @tmux-dotbar-bg         "#1e1f25"
set -g @tmux-dotbar-fg         "#33353a"
set -g @tmux-dotbar-fg-current "#adc6ff"
set -g @tmux-dotbar-fg-session "#adc6ff"
set -g @tmux-dotbar-fg-prefix  "#adc6ff"

set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default

