set -g status-bg                "#131318"

set -g @tmux-dotbar-bg         "#1f1f25"
set -g @tmux-dotbar-fg         "#35343a"
set -g @tmux-dotbar-fg-current "#c1c1ff"
set -g @tmux-dotbar-fg-session "#c1c1ff"
set -g @tmux-dotbar-fg-prefix  "#c1c1ff"

set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default

