set -g status-bg                "#111318"

set -g @tmux-dotbar-bg         "#1d2024"
set -g @tmux-dotbar-fg         "#32353a"
set -g @tmux-dotbar-fg-current "#a7c8ff"
set -g @tmux-dotbar-fg-session "#a7c8ff"
set -g @tmux-dotbar-fg-prefix  "#a7c8ff"

set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default

