exec = hyprctl dispatch submap global
exec = submap global

exec-once = swaync
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2 silent] $browser
exec-once = hyprctl dispatch exec "[workspace 3] spotify"
# exec-once = ashell --config-path ~/.config/ashell & hyprpaper & waypaper --restore
exec-once = hyprpaper & waypaper --restore & qs

