exec = hyprctl dispatch submap global
exec = submap global

exec-once = swaync
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 2] $browser
exec-once = hyprctl dispatch exec "[workspace 3] spotify"
# exec-once = qs --path ~/dotfiles/quickshell
# exec-once = qs -c noctalia-shell
# exec-once = noctalia-shell &
exec-once = hyprctl dispatch exec "wayle panel start"
exec-once = hyprctl setcursor capitaine-cursors 32

## Wallpaper
source = wallpaper.conf

