## hyprpaper
# exec-once = ashell --config-path ~/.config/ashell & hyprpaper & waypaper --restore

## awww
# exec-once = hyprctl dispatch exec "awww-daemon"

## swaybg
exec-once = hyprpaper & swaybg & waypaper --restore
