set -g status-bg                "#16130b"

set -g @tmux-dotbar-bg         "#221f17"
set -g @tmux-dotbar-fg         "#38352b"
set -g @tmux-dotbar-fg-current "#dcc66e"
set -g @tmux-dotbar-fg-session "#dcc66e"
set -g @tmux-dotbar-fg-prefix  "#dcc66e"

set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default

