imports = ["./matugen/colors.toml"]

[general]
font-sans = "JetBrainsMono Nerd Font"

[bar]
scale = 0.55
module-gap = 0.6
background-opacity = 100
rounding = "none"
button-variant = "basic"
button-gap = 1.2
button-label-size = 1.2
button-label-weight = "bold"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "hyprland-workspaces",
    "clock",
    "weather",
]
center = ["window-title"]
right = [
    "battery",
    "separator",
    "network",
    "separator",
    "volume",
    "separator",
    "systray",
    "separator",
    "dashboard",
]

[modules.clock]
format = "%a, %b %d, %Y %I:%M %p"
button-bg-color = "transparent"
label-color = "fg-default"
icon-show = false
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.dashboard]
icon-color = "fg-default"
icon-bg-color = "transparent"
dropdown-poweroff-command = "hyprshutdown -t 'Shutting down...' --post-cmd 'shutdown -P 0'"
dropdown-reboot-command = "hyprshutdown -t 'Rebooting...' --post-cmd 'reboot'"

[modules.hyprland-workspaces]
active-indicator = "underline"
active-color = "blue"
container-bg-color = "transparent"

[modules.window-title]
button-bg-color = "transparent"
icon-color = "fg-default"
icon-bg-color = "transparent"
label-color = "fg-default"

[modules.battery]
button-bg-color = "transparent"
label-color = "fg-default"
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.network]
button-bg-color = "transparent"
label-color = "fg-default"
label-show = false
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.volume]
button-bg-color = "transparent"
label-color = "fg-default"
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.systray]
button-bg-color = "transparent"
label-color = "fg-default"
icon-color = "fg-default"
icon-bg-color = "transparent"

[modules.media]
icon-show = false
label-color = "fg-default"
label-max-length = 20

[modules.weather]
location = "Manila"
button-bg-color = "transparent"
label-color = "fg-default"
icon-color = "fg-default"
icon-bg-color = "transparent"

