-- This file is autogenerated by Matugen! Edit the matugen file instead.
require('main.source_matugen')

return {
  'nvim-lualine/lualine.nvim',
  dependencies = {
    'RRethy/base16-nvim',
    'xiyaowong/transparent.nvim',
  },
  config = function()
    require('base16-colorscheme').setup({
      base00 = '{{colors.background.default.hex }}',
      base01 = '{{colors.surface_container_lowest.default.hex | lighten: +5}}',
      base02 = '{{colors.surface_container_low.default.hex | lighten: +10}}',
      base03 = '{{colors.outline_variant.default.hex | lighten: +10}}',
      base04 = '{{colors.on_surface_variant.default.hex}}',
      base05 = '{{colors.on_surface.default.hex}}',
      base06 = '{{colors.inverse_on_surface.default.hex}}',
      base07 = '{{colors.surface_bright.default.hex}}',
      base08 = '{{colors.tertiary.default.hex }}',
      base09 = '{{colors.tertiary.default.hex}}',
      base0A = '{{colors.secondary.default.hex}}',
      base0B = '{{colors.primary.default.hex}}',
      base0C = '{{colors.tertiary_container.default.hex}}',
      base0D = '{{colors.primary_container.default.hex | lighten: +25}}',
      base0E = '{{colors.secondary_container.default.hex | lighten: +25}}',
      base0F = '{{colors.secondary.default.hex }}',
    })

    vim.api.nvim_set_hl(0, 'Visual', {
      bg = '{{colors.primary_container.default.hex}}',
      fg = '{{colors.background.default.hex}}',
    })

    local function auxiliary_function()
      -- Load the matugen style file to get all the new colors
      source_matugen()

      -- Because reloading base16 overwrites lualine configuration, just source lualine here
      dofile(os.getenv('HOME') .. '/dotfiles/nvim/lua/plugins/ui.lua') -- path of your lualine setup

      -- Any other options you wish to set upon matugen reloads can also go here!
      vim.api.nvim_set_hl(0, 'Comment', { italic = true })
    end

    vim.api.nvim_create_autocmd('Signal', {
      pattern = 'SIGUSR1',
      callback = auxiliary_function,
    })

    -- Optional, you don't have to run setup.
    require("transparent").setup({
      -- table: default groups
      groups = {
        'Normal', 'NormalNC', 'Comment', 'Constant', 'Special', 'Identifier',
        'Statement', 'PreProc', 'Type', 'Underlined', 'Todo', 'String', 'Function',
        'Conditional', 'Repeat', 'Operator', 'Structure', 'LineNr', 'NonText',
        'SignColumn', 'CursorLine', 'CursorLineNr', 'StatusLine', 'StatusLineNC',
        'EndOfBuffer',
      },
      -- table: additional groups that should be cleared
      extra_groups = {},
      -- table: groups you don't want to clear
      exclude_groups = {},
      -- function: code to be executed after highlight groups are cleared
      -- Also the user event "TransparentClear" will be triggered
      on_clear = function() end,
    })

    require('lualine').setup({
      options = {
        icons_enabled = true,
        theme = 'base16',
        component_seperators = { left = ' ', right = ' ' },
        section_seperators = { left = ' ', right = ' ' },
        globalstatus = true,
      },
      sections = {
        lualine_a = { {
          'buffers',
        } },
      },
    })
  end,
}
